env = Environment(CPPPATH=["."], CPPFLAGS="-Wall -Werror -std=c++14 -g", CFLAGS="-std=c99")


# Source section
sources = Split("""
vm.cpp
instruction_set.cpp
mutator.cpp
optimizer.cpp
""")


# Object section
objects = env.Object(source = sources)


# Target section
interpreter = env.Program(target = "brainhug",
        source = objects + env.Object(source = "interpreter.cpp"))

test = env.Program(target = "test",
        source = objects + env.Object(source = "test.cpp"))

