env = Environment(CPPPATH=["."], CPPFLAGS="-Wall -Werror -std=c++14 -g", CFLAGS="-std=c99")


# Source section
sources = Split("""
main.cpp
vm.cpp
instruction_set.cpp
""")


# Object section
objects = env.Object(source = sources)


# Target section
binary = env.Program(target = "bin", source = objects)

